# authentication configuration for each Access URL
# Access URL Id / authentication method / params
parameters:
    authentication:
        1:
            generic:
                enabled: false
                client_id: ''
                client_secret: ''
                provider_options:
                    urlAuthorize: ''
                    urlAccessToken: ''
                    urlResourceOwnerDetails: ''
                    responseResourceOwnerId: 'sub'
                    accessTokenMethod: 'POST'
                    scopes:
                        - openid
                allow_create_new_users: true
                allow_update_user_info: false
                resource_owner_username_field: null
                resource_owner_firstname_field: null
                resource_owner_lastname_field: null
                resource_owner_email_field: null
                resource_owner_status_field: null
                resource_owner_teacher_status_field: null
                resource_owner_sessadmin_status_field: null
                resource_owner_hr_status_field: null
                resource_owner_status_status_field: null
                resource_owner_anon_status_field: null

            facebook:
                enabled: false
                client_id: ''
                client_secret: ''
                graph_api_version: 'v20.0'
                redirect_params: { }
